### ISSUE TITLE
Keycloak 17.0.0

### ISSUE THREAD

**Issue by olivierboudet** [bitnami/bitnami-docker-keycloak#46]
### Name and Version

bitnami/keycloak:17.0.0

### What is the problem this feature will solve?

Hello,
Keycloak 17.0.0 is released, with official support for Quarkus enabled by default.
What is the plan for bitnami keycloak image ?

### What is the feature you are proposing to solve the problem?

I would love to have the choice to use bitnami/keycloak:17.0.0-legacy (with jboss distribution) OR bitnami/keycloak:17.0.0 (with quarkus distribution)

**Comment by javsalgar** [comment]
Hi,

We will need to evaluate this. At the moment our automations will not allow having the two distros, so we will need to stick to one. Let's see if more people from the community add more feedback.

**Comment by DavidKittleSEL** [comment]
We are really interested in the new Quarkus runtime, our initial testing shows it starting up ~5x faster than the wildfly version of keycloak, while using less ram. We would like to see the chart support the new version.

**Comment by GreenCappuccino** [comment]
Chart issue: https://github.com/bitnami/charts/issues/9061 
Note that running Quarkus is definitely preferred in the future, as 17.0.0. release notes specify that they will only "continue to support the WildFly distribution until June 2022". With 3-4 months it might be worth focusing on this image compared to also supporting WildFly?

Just some musings from an outsider.

**Comment by javsalgar** [comment]
Thank you so much! I will forward this to the engineering team.

**Comment by dpulrichth** [comment]
Hi, 

are there any updates on this, possibly even a rough estimate when a Quarkus based image / chart will be available?

**Comment by wernert75** [comment]
We are very interested in using Quarkus based Keycloak. I think further versions of Keycloak will be based on quarkus only.

**Comment by javsalgar** [comment]
Hi!

I'm afraid this is still in our backlog. As soon as there are news, we will update the ticket.

**Comment by szlachet** [comment]
Hi,
any updates? We are very interested in about plans for bitnami keycloak image 17.0.0. Thanks in advance.

**Comment by javsalgar** [comment]
@Mauraza is working on the new release and I think she is performing major changes in the container code.

**Comment by Mauraza** [comment]
Yes, I'm working, and as @javsalgar said there are major changes (now keycloak uses Quarkus).
When the container will be released I will update this thread.

**Comment by fmendez89** [comment]
That's great news! 
Thanks for the update @Mauraza

**Comment by taoyonggang** [comment]
04:13:46,164 INFO  [org.infinispan.CONFIG] (MSC service thread 1-2) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.

 04:13:46,763 ERROR [org.infinispan.CLUSTER] (thread-7,ejb,camunda-platform-key-0) ISPN000475: Error processing response for request 2 from keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')

 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)

 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)

 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)

 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:252)

 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:235)

 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)

 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:72)

 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:60)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1407)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1317)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)

 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)

 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)

 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)

 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)

 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

 	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)

 	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)

 	at java.base/java.lang.Thread.run(Thread.java:829)

 

 04:13:46,763 ERROR [org.infinispan.CLUSTER] (thread-6,ejb,camunda-platform-key-0) ISPN000474: Error processing request 0@keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')

 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)

 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)

 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)

 	at org.infinispan@12.1.7.Final//org.infinispan.commands.topology.RebalanceStartCommand.readFrom(RebalanceStartCommand.java:98)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1374)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)

 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)

 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)

 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:363)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:355)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)

 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)

 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

 	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)

 	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)

 	at java.base/java.lang.Thread.run(Thread.java:829)

 

 04:13:46,763 ERROR [org.infinispan.CLUSTER] (thread-12,ejb,camunda-platform-key-0) ISPN000474: Error processing request 0@keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')

 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)

 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)

 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)

 	at org.infinispan@12.1.7.Final//org.infinispan.commands.topology.RebalanceStartCommand.readFrom(RebalanceStartCommand.java:98)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)

 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1374)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)

 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)

 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)

 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)

 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:363)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:355)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)

 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)

 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)

 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

 	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)

 	at org.jboss.as.clustering.common@26.0.1.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)

 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by carrodher** [comment]
@taoyonggang I just saw you created a specific issue for your error (https://github.com/bitnami/charts/issues/9871). We will provide an answer into that ticket; please let's try to no mix unrelated topics

**Comment by howels** [comment]
Any ETA on the version 17 update please?

**Comment by carrodher** [comment]
Unfortunately due to other priorities, we can't provide an ETA. We are working on the migration from Keycloak 16.x.x to 17.x.x and 18.x.x; since the backend was modified the changes are not trivial so the whole build, test & release pipeline needs to be adapted to the new logic.

We will update this thread once released the new version.

**Comment by GreenCappuccino** [comment]
Looks like a new build went through with Keycloak 17, along with the Helm chart. Does this mean that the image is ready now? Do you guys have any notes on migrating Keycloak 16 installations?

**Comment by carrodher** [comment]
In terms of the container image, there is a new branch for Keycloak 17.x.x, see https://github.com/bitnami/bitnami-docker-keycloak/commit/499ef7975b7537466cca853ed86e4ed7c341ad64

Regarding the Helm chart, there is a new major version bundling Keycloak 17.x.x (associated PR https://github.com/bitnami/charts/pull/10095):
```console
$ helm repo update bitnami
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈

$ helm search repo bitnami/keycloak
NAME            	CHART VERSION	APP VERSION	DESCRIPTION
bitnami/keycloak	8.0.0        	17.0.1     	Keycloak is a high performance Java-based ident...
```

We will work now on releasing Keycloak 18.x.x, but we didn't want to move directly from 16.x.x to 18.x.x without releasing at least one version of 17.x.x

**Comment by wernert75** [comment]
Great!
Is there some documentation for the migration from kc 16 to kc 17 using the helm-charts

**Comment by javsalgar** [comment]
Hi!

My advice would be to check the upstream documentation: https://www.keycloak.org/docs/latest/upgrading/index.html
