### ISSUE TITLE
1, version:7.0 ~ 7.1 2, depoly with chart 3, keycloak throw error and exit

### ISSUE THREAD

**Issue by taoyonggang** [bitnami/bitnami-docker-keycloak#54]
### Name and Version

bitnami/bitnami-docker-keycloak:16

### What steps will reproduce the bug?

1, version:16.0~16.1 ,for examlpe : bitnami/keycloak:16.1.1-debian-10-r85
2, The keycloak image throw error and exit.

The error:

'''
02:58:49,086 INFO  [org.infinispan.CONFIG] (MSC service thread 1-2) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-7,ejb,camunda-platform-key-0) ISPN000474: Error processing request 0@keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap') 	
    at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
    at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400) 	
    at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32) 	
    at org.infinispan@12.1.7.Final//org.infinispan.commands.topology.RebalanceStartCommand.readFrom(RebalanceStartCommand.java:98) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68) 	
    at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1374)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
 	at java.base/java.lang.Thread.run(Thread.java:829)

 02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-6,ejb,camunda-platform-key-0) ISPN000475: Error processing response for request 2 from keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:252)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:235)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:72)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:60)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1407)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1317)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
 	at java.base/java.lang.Thread.run(Thread.java:829)

 02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-12,ejb,camunda-platform-key-0) ISPN000474: Error processing request 0@keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.commands.topology.RebalanceStartCommand.readFrom(RebalanceStartCommand.java:98)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandParameters(ReplicableCommandExternalizer.java:117)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:106)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readObject(ReplicableCommandExternalizer.java:68)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processRequest(JGroupsTransport.java:1374)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1314)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:363)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:355)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:392)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.deliver(NAKACK2.java:926)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.handleMessage(NAKACK2.java:818)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:602)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FailureDetection.up(FailureDetection.java:186)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FD_SOCK.up(FD_SOCK.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.MERGE3.up(MERGE3.java:281)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Discovery.up(Discovery.java:300)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.TP.passMessageUp(TP.java:1400)
 	at org.jgroups@4.2.15.Final//org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:98)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextReferenceExecutor.execute(ContextReferenceExecutor.java:49)
 	at org.jboss.as.clustering.common@26.0.0.Final//org.jboss.as.clustering.context.ContextualExecutor$1.run(ContextualExecutor.java:70)
 	at java.base/java.lang.Thread.run(Thread.java:829)

 02:58:49,614 ERROR [org.infinispan.CLUSTER] (thread-9,ejb,camunda-platform-key-0) ISPN000475: Error processing response for request 2 from keycloak-5594896f99-k4twh: java.lang.ClassCastException: class [I cannot be cast to class java.util.Map ([I and java.util.Map are in module java.base of loader 'bootstrap')
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:415)
 	at org.infinispan@12.1.7.Final//org.infinispan.distribution.ch.impl.ReplicatedConsistentHash$Externalizer.doReadObject(ReplicatedConsistentHash.java:400)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:252)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheTopology$Externalizer.doReadObject(CacheTopology.java:235)
 	at org.infinispan.commons@12.1.7.Final//org.infinispan.commons.marshall.InstanceReusingAdvancedExternalizer.readObject(InstanceReusingAdvancedExternalizer.java:102)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:72)
 	at org.infinispan@12.1.7.Final//org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:60)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
 	at org.infinispan@12.1.7.Final//org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1407)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1317)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport.access$300(JGroupsTransport.java:133)
 	at org.infinispan@12.1.7.Final//org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1458)
 	at org.jgroups@4.2.15.Final//org.jgroups.JChannel.up(JChannel.java:784)
 	at org.jgroups@4.2.15.Final//org.jgroups.fork.ForkProtocolStack.up(ForkProtocolStack.java:135)
 	at org.jgroups@4.2.15.Final//org.jgroups.stack.Protocol.up(Protocol.java:309)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FORK.up(FORK.java:142)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FRAG3.up(FRAG3.java:165)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.FlowControl.up(FlowControl.java:347)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.GMS.up(GMS.java:876)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:254)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1048)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:771)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:752)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.UNICAST3.up(UNICAST3.java:405)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:592)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.VERIFY_SUSPECT.up(VERIFY_SUSPECT.java:132)
 	at org.jgroups@4.2.15.Final//org.jgroups.protocols.Fa
'''

### What do you see instead?

The version 15 is ok.

**Comment by rafariossaa** [comment]
Hi,
  Could you indicate the parameters you used ? I would like to reproduce the issue on my side.
